/**
 * NegotiationStrategy — Counter offer, reasoning, and talk track.
 * Refined typography matching the minimal homepage style.
 */

export default function NegotiationStrategy({ result }) {
  if (!result) return null;

  return (
    <div className="space-y-5 animate-fade-in">
      {/* Section title */}
      <h2 className="font-display font-bold text-[1.1rem] text-slate-800 tracking-tight">
        Negotiation Strategy
      </h2>

      {/* Suggested Counter Offer */}
      {result.suggested_price && (
        <div className="card p-6 text-center border-robin-200/60 bg-robin-50/30">
          <p className="text-[11px] font-semibold text-slate-400 uppercase tracking-[0.15em] mb-3">
            Suggested Counter Offer
          </p>
          <p className="text-[2rem] font-display font-black text-robin-700 tracking-tight mb-2">
            {result.suggested_price}
          </p>
          <div className="flex items-center justify-center gap-3 text-[12px]">
            <span className="badge-low">Fair &amp; Reasonable</span>
            {result.improvement_pct && (
              <span className="text-robin-600 font-bold">
                {result.improvement_pct} improvement
              </span>
            )}
          </div>
        </div>
      )}

      {/* Why this price? */}
      {result.price_reasoning?.length > 0 && (
        <div className="card p-5">
          <h3 className="text-[11px] font-semibold text-slate-400 uppercase tracking-[0.15em] mb-4">
            Why This Price
          </h3>
          <ul className="space-y-3">
            {result.price_reasoning.map((reason, index) => (
              <li key={index} className="flex items-start gap-3">
                <span className="flex-shrink-0 w-5 h-5 rounded-full bg-robin-100 text-robin-700 flex items-center justify-center mt-0.5">
                  <CheckIcon className="w-3 h-3" />
                </span>
                <span className="text-[13px] text-slate-700 leading-relaxed">{reason}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Talk Track */}
      {result.negotiation_points?.length > 0 && (
        <div className="card p-5">
          <h3 className="text-[11px] font-semibold text-slate-400 uppercase tracking-[0.15em] mb-4">
            Talk Track
          </h3>
          <ol className="space-y-3">
            {result.negotiation_points.map((point, index) => (
              <li key={index} className="flex items-start gap-3">
                <span className="flex-shrink-0 w-5 h-5 rounded-full bg-slate-100 text-slate-600 flex items-center justify-center text-[10px] font-bold mt-0.5">
                  {index + 1}
                </span>
                <span className="text-[13px] text-slate-700 leading-relaxed">{point}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Download button */}
      <button
        onClick={() => downloadStrategy(result)}
        className="btn-primary w-full flex items-center justify-center gap-2.5 py-3.5 text-[13px] font-semibold tracking-wide"
        id="download-strategy-button"
      >
        <DownloadIcon className="w-4 h-4" />
        <span>Download Strategy</span>
      </button>
    </div>
  );
}


/** Export strategy as a text file */
function downloadStrategy(result) {
  const lines = [
    'ROBIN-HOOD AI — NEGOTIATION STRATEGY',
    '='.repeat(40),
    '',
    `Suggested Counter Offer: ${result.suggested_price || 'N/A'}`,
    `Potential Improvement: ${result.improvement_pct || 'N/A'}`,
    `Confidence: ${result.confidence || 'N/A'}`,
    '',
    'WHY THIS PRICE:',
    ...(result.price_reasoning || []).map((r, i) => `  ${i + 1}. ${r}`),
    '',
    'NEGOTIATION POINTS:',
    ...(result.negotiation_points || []).map((p, i) => `  ${i + 1}. ${p}`),
    '',
    'SUMMARY:',
    result.summary || 'N/A',
    '',
    '---',
    'Generated by Robin-Hood AI',
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'negotiation-strategy.txt';
  a.click();
  URL.revokeObjectURL(url);
}


function CheckIcon({ className = '' }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

function DownloadIcon({ className = '' }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
}
